# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4241840569b1c86de3dd2e1f95252c44208c4266a08249cafaeb00c659704cb825c2efdf13993365e6661d1bf2a2caf36ad38ad453fc0b0ef41c9f86b0cd911f

test:
  secret_key_base: 4d58f328e5ef468fb8fba496303806d12b6e69727fb1208acb6c6d07d897aded698dfac0c66e01585de192477ba773396fc791cd149e23e849b91d3a04cca1c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
